version: "3.1"
services:
  website:
    build: .
    restart: always
    container_name: website
    ports:
      - 8383:80
    depends_on:
      - db
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./myqsl/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: website
      MYSQL_USER: website
      MYSQL_PASSWORD: website
      TZ: Europe/Brussels

  admin:
    image: phpmyadmin/phpmyadmin
    container_name: admin
    restart: always
    ports:
      - 8181:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
